### ISSUE TITLE
yaml codeblocks are not highlighted correctly 

### ISSUE THREAD

**Issue by joelostblom** [vim-pandoc/vim-pandoc-syntax#224]
When I create a codeblock with a yaml snippet, I have noticed that `vim-pandoc-syntax` hides the first few lines. I need to introduce a blank line either above or below the leading `---` to display the entire codeblock in vim. However, this introducing an unnecessary blank line in the rendered code block, so it would be nice if something like the sample below, was displayed correctly.

```yaml
---
object:
    key: value
    array:
        - null_value:
        - boolean: true
        - integer: 1
---
```

For me, when I place the this snippet in a `.md` file with at least one blank line above it, only `- integer: 1` is displayed.
