### ISSUE TITLE
Set up commentring in the document's YAML metadata region

### ISSUE THREAD

**Issue by krishnakumarg1984** [vim-pandoc/vim-pandoc-syntax#298]
Unsure if this issue should be filed in the main plugin repo or here.

If the buffer's filetype is set to `pandoc`, the appropriate `vim-pandoc` sub-project must set the `commentring` variable in the appropriate `yaml` metadata region for the document. This will aid the writer's workflow by integrating with the various commenting plugins (tcomment, commentary etc.)

eg.

```
---
title: 'Eating Habits'
author: John Doe
date: March 22, 2005
# parallaxBackgroundImage: ./images/leaves_bg.jpg
pandocomatic_:
  use-template:
    - md_to_beamer_basic_pdf
    # - md_to_pptx_basic
    - md_to_revealjs_with_Mathjax
  pandoc:
    incremental: true
    # css:
    # - reveal.js/css/theme/solarized.css
  metadata:
    theme: metropolis
---
```

This is the yaml-metadata block for the document. I'd like to comment and uncomment various sections eg. the `css` property. I could just use `gcj` with `tcomment` if the plugin sets the yaml codeblock's local `commentstring` to `#`  and then back to the standard HTML commenting in the rest of the buffer.
